
//CHANNELS
export const POLL_CHANNELS = 'POLL_CHANNELS';

export const POLL_NODES= 'POLL_NODES';


//DASHBOARD
export const DASHBOARD_DATA_SUCCEED = 'DASHBOAR_DATA_SUCCEED';

//FEED
export const FEED_DATA_SUCCEED = 'FEED_DATA_SUCCEED';

//SEARCH
export const UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE';
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';
export const LOAD_SUGGESTIONS_BEGIN = 'LOAD_SUGGESTIONS_BEGIN';
export const MAYBE_UPDATE_SUGGESTIONS = 'MAYBE_UPDATE_SUGGESTIONS';
export const NO_SUGGESTIONS = 'NO_SUGGESTIONS';
export const SUGGESTION = 'SUGGESTION';

